Change jenkinsfile moved upload report always even test failed

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -45,21 +45,16 @@ pipeline {
                     allure includeProperties: false, jdk: '', results: [[path: 'build/allure-results']]
                     echo 'Subiendo resultados a Xray...'
                     sh 'chmod +x ./upload-xray.sh && ./upload-xray.sh'
+                    echo 'Generando PDF con Puppeteer...'
+                    sh '''
+                        if ! command -v node >/dev/null 2>&1; then
+                            echo "Node.js no está instalado. Abortando."
+                            exit 1
+                        fi
+                        chmod +x ./generate-and-upload-pdf.sh
+                        ./generate-and-upload-pdf.sh
+                    '''
                 }
-            }
-        }
-
-        stage('Generar PDF Allure Report') {
-            steps {
-                echo 'Generando PDF con Puppeteer...'
-                sh '''
-                    if ! command -v node >/dev/null 2>&1; then
-                        echo "Node.js no está instalado. Abortando."
-                        exit 1
-                    fi
-                    chmod +x ./generate-and-upload-pdf.sh
-                    ./generate-and-upload-pdf.sh
-                '''
             }
         }
     }
